### ISSUE TITLE
Error when running evaluate.py

### ISSUE THREAD

**Issue by vidyaa29** [NVlabs/ScePT#5] opened 2022-11-15 00:42 UTC
When running evaluate.py, the predict() in ScePT is called with parameters gmm_mode and z_mode which throws an error, since there is no implementation with these parameters. I am trying to re-implement the ScePT code and find the ADE & FDE errors for the 100th checkpoint. Please help me resolve the issue.

Thanks,
Vidyaa

**Comment by chenyx09** [comment] 2022-12-01 18:32
Hi Vidyaa, I'll take a look soon.

**Comment by chenyx09** [comment] 2022-12-08 19:57
Hi Vidyaa, sorry for the delay, I just pushed a fix, and you can try following the instruction in the readme. Please let me know if the issue is not resolved.

**Comment by vidyaa29** [comment] 2022-12-15 19:54
Hi chenyx09,

Thanks for the reply! It works fine now.

**Closed** 2022-12-15 22:31 UTC
